AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  handler:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda example for trying to understand async/await.
      Runtime: nodejs12.x
      Handler: built/async.handler
      MemorySize: 512
      Timeout: 100
